CRITICAL - 2023-03-30 01:44:15 --> syntax error, unexpected 'die' (T_EXIT), expecting ';' or ','
in APPPATH\Views\ProductoEditor.php on line 10.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('ProductoEditor', [], true)
 3 APPPATH\Controllers\ProductoEditor.php(22): view('ProductoEditor', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoEditor->agregar()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoEditor))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 01:44:17 --> syntax error, unexpected 'die' (T_EXIT), expecting ';' or ','
in APPPATH\Views\ProductoEditor.php on line 10.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('ProductoEditor', [], true)
 3 APPPATH\Controllers\ProductoEditor.php(22): view('ProductoEditor', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoEditor->agregar()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoEditor))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 02:38:54 --> Cannot redeclare App\Controllers\ProductoBaseDatosCRUD::index()
in APPPATH\Controllers\ProductoBaseDatosCRUD.php on line 11.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-03-30 03:02:06 --> Call to undefined method App\Controllers\ProductoBaseDatosCRUD::respond()
in APPPATH\Controllers\ProductoBaseDatosCRUD.php on line 9.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 03:44:04 --> syntax error, unexpected '$datos_post' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
in APPPATH\Controllers\ProductoBaseDatosCRUD.php on line 9.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('G:\\xampp74330_w\\htdocs\\ejemplo301nube.com\\folder_ww\\app\\Controllers\\ProductoBaseDatosCRUD.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\ProductoBaseDatosCRUD')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\ProductoBaseDatosCRUD')
 4 [internal function]: spl_autoload_call('App\\Controllers\\ProductoBaseDatosCRUD')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\ProductoBaseDatosCRUD', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 03:44:41 --> syntax error, unexpected '$datos_post' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
in APPPATH\Controllers\ProductoBaseDatosCRUD.php on line 9.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('G:\\xampp74330_w\\htdocs\\ejemplo301nube.com\\folder_ww\\app\\Controllers\\ProductoBaseDatosCRUD.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\ProductoBaseDatosCRUD')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\ProductoBaseDatosCRUD')
 4 [internal function]: spl_autoload_call('App\\Controllers\\ProductoBaseDatosCRUD')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\ProductoBaseDatosCRUD', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 03:45:08 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 1680.
 1 SYSTEMPATH\BaseModel.php(1680): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\BaseModel.php(742): CodeIgniter\BaseModel->transformDataToArray(null, 'insert')
 3 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert(null, true)
 4 APPPATH\Controllers\ProductoBaseDatosCRUD.php(55): CodeIgniter\Model->insert(null)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 03:45:29 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 1680.
 1 SYSTEMPATH\BaseModel.php(1680): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\BaseModel.php(742): CodeIgniter\BaseModel->transformDataToArray(null, 'insert')
 3 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert(null, true)
 4 APPPATH\Controllers\ProductoBaseDatosCRUD.php(55): CodeIgniter\Model->insert(null)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 03:46:34 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 1680.
 1 SYSTEMPATH\BaseModel.php(1680): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\BaseModel.php(742): CodeIgniter\BaseModel->transformDataToArray(null, 'insert')
 3 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert(null, true)
 4 APPPATH\Controllers\ProductoBaseDatosCRUD.php(55): CodeIgniter\Model->insert(null)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 03:47:05 --> syntax error, unexpected '$datos_post' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
in APPPATH\Controllers\ProductoBaseDatosCRUD.php on line 9.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('G:\\xampp74330_w\\htdocs\\ejemplo301nube.com\\folder_ww\\app\\Controllers\\ProductoBaseDatosCRUD.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\ProductoBaseDatosCRUD')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\ProductoBaseDatosCRUD')
 4 [internal function]: spl_autoload_call('App\\Controllers\\ProductoBaseDatosCRUD')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\ProductoBaseDatosCRUD', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 03:47:27 --> syntax error, unexpected '$datos_post' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
in APPPATH\Controllers\ProductoBaseDatosCRUD.php on line 9.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('G:\\xampp74330_w\\htdocs\\ejemplo301nube.com\\folder_ww\\app\\Controllers\\ProductoBaseDatosCRUD.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\ProductoBaseDatosCRUD')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\ProductoBaseDatosCRUD')
 4 [internal function]: spl_autoload_call('App\\Controllers\\ProductoBaseDatosCRUD')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\ProductoBaseDatosCRUD', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 03:47:42 --> syntax error, unexpected '$datos_post' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
in APPPATH\Controllers\ProductoBaseDatosCRUD.php on line 9.
 1 SYSTEMPATH\Autoloader\Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('G:\\xampp74330_w\\htdocs\\ejemplo301nube.com\\folder_ww\\app\\Controllers\\ProductoBaseDatosCRUD.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\ProductoBaseDatosCRUD')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\ProductoBaseDatosCRUD')
 4 [internal function]: spl_autoload_call('App\\Controllers\\ProductoBaseDatosCRUD')
 5 SYSTEMPATH\CodeIgniter.php(892): class_exists('\\App\\Controllers\\ProductoBaseDatosCRUD', true)
 6 SYSTEMPATH\CodeIgniter.php(486): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 03:47:58 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 1680.
 1 SYSTEMPATH\BaseModel.php(1680): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\BaseModel.php(742): CodeIgniter\BaseModel->transformDataToArray(null, 'insert')
 3 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert(null, true)
 4 APPPATH\Controllers\ProductoBaseDatosCRUD.php(54): CodeIgniter\Model->insert(null)
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 03:53:00 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(54): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(54): CodeIgniter\Model->insert(Array)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-03-30 03:53:00 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `USERS` (`email`) VALUES (:email:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoBaseDatosCRUD.php(54): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 03:53:45 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-03-30 03:53:45 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `USERS` (`email`) VALUES (:email:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 03:54:39 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-03-30 03:54:39 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `USERS` (`email`) VALUES (:email:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 03:55:05 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-03-30 03:55:05 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `USERS` (`email`) VALUES (:email:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 03:56:08 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-03-30 03:56:08 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `USERS` (`email`) VALUES (:email:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 04:42:50 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root7', '00000000', 'ejemplo301nube', 3306, '', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-03-30 04:42:50 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `USERS` (`email`) VALUES (:email:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 05:23:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root7'@'localhost' (using password: YES) in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root7', '00000000', 'ejemplo301nube', 3306, '', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `US...', Array, false)
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-03-30 05:23:31 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `USERS` (`email`) VALUES (:email:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 05:29:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root7'@'localhost' (using password: YES) in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root7', '00000000', 'ejemplo301nube', 3306, '', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-03-30 05:29:46 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`email`) VALUES (:email:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 05:30:47 --> mysqli_sql_exception: Unknown column 'email' in 'field list' in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `pr...', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-30 05:30:47 --> Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `productos` (`email`) VALUES (NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `productos` (`email`) VALUES (NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `productos` (`email`) VALUES (NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`email`) VALUES (:email:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 05:31:45 --> mysqli_sql_exception: Unknown column 'email' in 'field list' in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `pr...', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-30 05:31:45 --> Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `productos` (`email`) VALUES (NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `productos` (`email`) VALUES (NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `productos` (`email`) VALUES (NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`email`) VALUES (:email:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 05:33:10 --> mysqli_sql_exception: Unknown column 'email' in 'field list' in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `pr...', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-30 05:33:10 --> Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `productos` (`email`) VALUES (NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `productos` (`email`) VALUES (NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `productos` (`email`) VALUES (NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`email`) VALUES (:email:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 05:38:36 --> mysqli_sql_exception: Unknown column 'email' in 'field list' in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `pr...', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-30 05:38:36 --> Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `productos` (`email`) VALUES (NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `productos` (`email`) VALUES (NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `productos` (`email`) VALUES (NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`email`) VALUES (:email:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 05:38:52 --> mysqli_sql_exception: Unknown column 'email' in 'field list' in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `pr...', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert(Array)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
#9 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
#10 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-30 05:38:52 --> Unknown column 'email' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `productos` (`email`) VALUES (NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `productos` (`email`) VALUES (NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `productos` (`email`) VALUES (NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`email`) VALUES (:email:)', [...], false)
 5 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ProductoBaseDatosCRUD.php(64): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\ProductoBaseDatosCRUD->insertartupla()
10 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductoBaseDatosCRUD))
11 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 16:52:35 --> Call to a member function query() on null
in APPPATH\Controllers\Productos.php on line 11.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Productos->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-30 17:18:55 --> syntax error, unexpected ';'
in APPPATH\Views\ProductosListado.php on line 43.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('ProductosListado', [], true)
 3 APPPATH\Controllers\Productos.php(19): view('ProductosListado', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Productos->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 17:57:14 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root7', '00000000', 'ejemplo301nube', 3306, '', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(836): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\Productos.php(15): CodeIgniter\Model->__call('query', Array)
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\Productos->index()
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(836): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\Productos.php(15): CodeIgniter\Model->__call('query', Array)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\Productos->index()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-03-30 17:57:14 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Model.php(836): CodeIgniter\Database\BaseConnection->query('SELECT * FROM productos')
 3 APPPATH\Controllers\Productos.php(15): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Productos->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-30 17:57:42 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root7', '00000000', 'ejemplo301nube', 3306, '', 0)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(836): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\Productos.php(15): CodeIgniter\Model->__call('query', Array)
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\Productos->index()
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\Model.php(836): CodeIgniter\Database\BaseConnection->query('SELECT * FROM p...')
#3 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\app\Controllers\Productos.php(15): CodeIgniter\Model->__call('query', Array)
#4 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(934): App\Controllers\Productos->index()
#5 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
#6 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 G:\xampp74330_w\htdocs\ejemplo301nube.com\folder_ww\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-03-30 17:57:42 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Model.php(836): CodeIgniter\Database\BaseConnection->query('SELECT * FROM productos')
 3 APPPATH\Controllers\Productos.php(15): CodeIgniter\Model->__call('query', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Productos->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
